version: '2.2'

services:
  redpanda:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://redpanda:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://redpanda:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.3
    container_name: redpanda
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    networks:
      - moots
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644
    restart: unless-stopped

  redisDB:
    container_name: redisDB
    image: redis:latest
    volumes:
      - redisDB-data:/data
    ports:
      - 6379:6379
      - 16379:16379
    networks:
      - moots
    restart: unless-stopped

  elasticsearch:
    container_name: elasticsearch
    image: bitnami/elasticsearch:latest
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - moots
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    restart: unless-stopped

  api-post:
    container_name: api-post
    image: emerson757/post-moots:v1
    environment:
      - SPRING.KAFKA.BOOTSTRAP-SERVERS=redpanda:19092
      - SPRING.REDIS.HOST=redisDB
      - SPRING.REDIS.PORT=6379
      - SPRING.DATA.REDIS.HOST=redisDB
      - SPRING.DATA.REDIS.PORT=6379
      - SPRING.NEO4J.URI=bolt://neo4j:7687
      - SPRING.NEO4J.AUTHENTICATION.USERNAME=neo4j
      - SPRING.NEO4J.AUTHENTICATION.PASSWORD=admin123
    ports:
      - 8081:8081
    depends_on:
      - redisDB
      - redpanda
      - neo4j
    networks:
      - moots
    restart: unless-stopped

  api-usuarios:
    container_name: api-usuarios
    image: emerson757/usuario-moots:v1
    environment:
      - SPRING.KAFKA.BOOTSTRAP-SERVERS=redpanda:19092
      - SPRING.REDIS.HOST=redisDB
      - SPRING.REDIS.PORT=6379
      - SPRING.DATA.REDIS.HOST=redisDB
      - SPRING.DATA.REDIS.PORT=6379
      - SPRING.NEO4J.URI=bolt://neo4j:7687
      - SPRING.NEO4J.AUTHENTICATION.USERNAME=neo4j
      - SPRING.NEO4J.AUTHENTICATION.PASSWORD=admin123
    ports:
      - 8083:8083
    depends_on:
      - redisDB
      - redpanda
      - neo4j
    networks:
      - moots
    restart: unless-stopped

  api-reporte:
    container_name: api-reporte
    image: emerson757/reporte-moots:v1
    environment:
      - SPRING.KAFKA.BOOTSTRAP-SERVERS=redpanda:19092
      - SPRING.REDIS.HOST=redisDB
      - SPRING.REDIS.PORT=6379
    ports:
      - 8082:8082
    depends_on:
      - redpanda
      - redisDB
    networks:
      - moots
    restart: unless-stopped

  api-notificacao:
    container_name: api-notificacao
    image: emerson757/notificacao-moots:v1
    environment:
      - SPRING.KAFKA.BOOTSTRAP-SERVERS=redpanda:19092
      - SPRING.REDIS.HOST=redisDB
      - SPRING.REDIS.PORT=6379
    ports:
      - 8084:8084
    depends_on:
      - redpanda
      - redisDB
    networks:
      - moots
    restart: unless-stopped

  api-busca:
    container_name: api-busca
    image: emerson757/busca-moots:v1
    environment:
      - SPRING_ELASTICSEARCH_URIS=elasticsearch:9200
      - SPRING.KAFKA.BOOTSTRAP-SERVERS=redpanda:19092
      - SPRING.REDIS.HOST=redisDB
      - SPRING.REDIS.PORT=6379
    ports:
      - 8085:8085
    depends_on:
      - elasticsearch
      - redpanda
      - redisDB
    networks:
      - moots
    restart: unless-stopped

  api-gateway:
    container_name: api-gateway
    image: emerson757/gateway-moots:v1
    ports:
      - 8080:8080
    depends_on:
      - api-post
      - api-usuarios
      - api-reporte
      - api-notificacao
      - api-busca
    networks:
      - moots
    restart: unless-stopped

  neo4j:
    container_name: neo4j
    image: neo4j:5-community
    environment:
      - NEO4J_AUTH=neo4j/admin123
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - moots
    volumes:
      - neo4j-data:/data
    restart: unless-stopped

  web:
    container_name: moots-web
    image: emerson757/web-moots:v1
    ports:
      - 3000:80
    networks:
      - moots
    depends_on:
      - api-post
      - api-usuarios
      - api-reporte
      - api-notificacao
      - api-busca
    restart: unless-stopped

networks:
  moots:
    driver: bridge

volumes:
  elasticsearch-data:
  neo4j-data:
  redpanda-data:
  redisDB-data:
    driver: local